name: "publish"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: "13.x"
          scope: "@minddoc"
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Lint code
        run: yarn lint
      - name: Test code
        run: yarn test
      - name: Build code
        run: yarn build
      - name: Publish the package
        run: |
          yarn config set npmPublishRegistry 'https://npm.pkg.github.com/'
          yarn config set npmAuthToken "$env:NODE_AUTH_TOKEN"
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MINDDOCBOT_TOKEN }}
