name: "publish"
on:
  release:
    types: [published]
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set env
        run: |
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
          echo $RELEASE_VERSION
      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@minddoc"
      - name: Publish the package
        run: |
          npm version $RELEASE_VERSION
          npm config set registry https://registry.npmjs.org
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
  publish-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - name: Set env
        run: |
          echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
          echo $RELEASE_VERSION
      - uses: actions/setup-node@v2
        with:
          node-version: "13.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@minddocdev"
      - name: Publish the package
        run: |
          npm version $RELEASE_VERSION
          npm config set name @minddocdev/nest-express-winston
          npm config set registry https://npm.pkg.github.com
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MINDDOCBOT_TOKEN }}
