name: "publish"
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-node@v1
        with:
          always-auth: true
          node-version: "13.x"
          scope: "@minddoc"
          registry-url: "https://registry.npmjs.org"
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Lint code
        run: yarn lint
      - name: Test code
        run: yarn test
      - name: Build code
        run: yarn build
      - name: Publish the package
        run: |
          npm config set registry 'https://registry.npmjs.org'
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MINDDOCBOT_TOKEN }}
