name: "release"
on:
  push:
    branches:
      - master
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: minddocdev/mou-release-action@master
        with:
          draft: false
          prerelease: false
          templatePath: RELEASE_DRAFT/default.md
          token: ${{ github.token }}
